cagnulein/qdomyos-zwift

src/m3ibike.cpp, src/m3ibike.h
Setting the bike ID is no more required if you don't have more than one bike (which is very likely).
=> Minor optimizations in m3ibike class

src/virtualbike.cpp
Appending a byte with zeros fixes an issue with the "BKOOL application" : the application has an offset of "+1280" on HR PPM value.
=> VIRTUALBIKE Append 0 byte object after HR

src/fitshowtreadmill.cpp, src/fitshowtreadmill.h, src/m3ibike.cpp
With this pull request I am introducing moving time to fitshowtradmill module and to m3i module. Fitshowtradmill code is pretty much similar to the one of the other treadmills. 
M3ibike elapsed time was already the moving time. m3i bike does not support the option value continuous_moving = true. The computed elapsed time and moving time are always equal and so they are both updated only when movements are detected.
=> Introducing moving time for m3i and fitshowtreadmill.

src/bluetooth.cpp, src/bluetooth.h, src/kingsmithr2treadmill.cpp, src/kingsmithr2treadmill.h, src/qdomyos-zwift.pro
this patch will support KingSmith R2 (Non PRO version)
- copy filtering device name from an original app. in my case KS-R1AC
- initial check connection on PC mode
it just copied&modified from `kingsmithr1protreadmill.cpp`. I'm not friendly with QT, code could have wrong & inefficiency part
a communication flow can find https://gist.github.com/d3m3vilurr/69b84ce4d57ed8c93b19c93600570394
=> Initial support KingSmith R2 (CN version)

docs/10_Installation.md
Modified the raspberry pi install instructions as the qt5-default package has been renamed qt5-assistant in the raspbian sources.
=> qt5package name change

docs/30_usage.md, src/main.cpp
I added a new parameter (-nordictrack-10-treadmill) for the command line to enable NordicTrack compatibility.
`sudo /home/pi/qdomyos-zwift/src/qdomyos-zwift -no-log -no-gui -heart-service -nordictrack-10-treadmill`
=> Activate "NordicTrack" compatibility mode from the command line

docs/30_usage.md
Parameter value is "`-nordictrack-10-treadmill`" and not "`--nordictrack-10-treadmill`" as previously edited.
=> Fix typo in parameters' list

src/gpiotreadmill.cpp, src/gpiotreadmill.h
This is my first implementation of the GPIO controlled treadmill.
It is a start but there is still something missing.
So it takes some time until my treadmill is set to speed. In the time no speed is transmitted to Zwift.
So changing the speed has to be done in another thread.
for testing it turned out that a trainings.xml file is a good possibility.
#525
=> Improve the setting of the speed and the slope

src/concept2skierg.cpp, src/concept2skierg.h
1. It seems only one subscription is needed.
2. Some metrics added.
3. Speed, cadence and watts forced to 0 when skierg is not active. Otherwise it keeps reporting old stale values.
TODO: Cleanup debug code.
Related issue: https://github.com/cagnulein/qdomyos-zwift/issues/573
=> adjust skierg metrics, and use one notification

src/templateinfosenderbuilder.cpp, src/templateinfosenderbuilder.h
This pull request implements 3 commands to control `qdosmyos` by WebSocket for issue #582.
Start who when `qdosmyos` is on pause resume or otherwise reset timer (and distance...) and start from new.
Pause who only pause `qdosmyos` when pause is not active.
Stop who stop `qdosmyos` and reset all data.
One of my problem of my PR is with the current `bluetoothdevice.h` I can't know if the state is on stop or start so start will always if the state is not on pause reset all data. After this is not very bad cause we can presume on the external side with "workout" state if the state the machine is running or not (if speed is at zero for example).
Second and last problem of my PR is I don't know how communicate from `templateinfosenderbuild.cpp` to `homeform.cpp` to update the UI state when I …
=> Add on Websocket start / pause / stop commands

src/settings.qml, src/smartspin2k.cpp, src/smartspin2k.h
SS2K Shift Step calibration
Add calibration of SS2K shift step by resistance level using least squares method.  Sampling of data points in configuration TBD
I'm thinking it could work like this:
1. For each of the data points, QZ would set the resistance on the SS2K.  
2. The user would pedal and tap +/- to adjust the shift step for that data point.   setShiftStep is called with the new value.
3. When the resistances match, they'd tap OK and move on to the next data point.
4. When all 4 data points are set, calibrateShiftStep is called to calculate the slope and intercept which are then saved to settings.
=> SS2K Shift Step calibration

src/peloton.cpp, src/peloton.h
Changes:
* (before) `/api/workout/<workout_id>/performance_graph?every_n=10` has a resolution of 10s which means that cues will always be off unless on a strict 10s mark
* (after) `/api/ride/<ride_id>/details` has exact cues
* Fallback using old logic
Test Plan:
* Normal ride cues are perfectly sync'd
* Power Zones & Treadmill do not have any cues (same as before my changes)
=> Improve Peloton cues

src/homeform.cpp, src/homeform.h, src/settings.qml, src/trainprogram.cpp, src/trainprogram.h
* Cadence and Resistance Tiles - Improve readability for bikes using red, limegreen, and orange for < min, <= max, < max respectively
* Peloton Offset Tile
* Rename to Peloton Remaining/Rem.
* Add remaining time to make it easier to match with Peloton app
* Swap remaining time with offset as remaining time is more useful
* Time to Next Tile
* Add Current Row Elapsed Time as secondary text
* Enable writing to skip forward/back to next/previous row
Note: Time To Next -/+ along with Peloton Remaining makes it super easy to catch up to the correct timestamp now!
=> Improve functionality for Peloton App users

src/nordictrackifitadbtreadmill.cpp
=> Adb.exe stays resident on QZ exit (Windows) (Issue #1951)

src/devices/skandikawiribike/skandikawiribike.cpp
The speed could not be calculated based on watt, because the code was in an unsolvable if query. I have changed the if query to "cadence", like on the Schwinn bike (and others). Now the speed is calculated correctly as soon as you pedal. Before this fix the option "calculate speed based on watt" had be turned off to get speed values.
This is a screenshot taken with "calculate speed based on watt" turned on. And as expected, the speed on bike display and the speed on qdomyos-zwift ​​differ greatly.
=> Skandika Morpheus: calc speed based on watts fixed

.github/workflows/main.yml
This PR updates the image to the current lite image
It also adds to the boot config the necessary line to get bluetooth working on raspberry pi zero 2W
Without the updated bootconfig with `dtoverlay=miniuart-bt` the build-in bluetooth is not found.
I expect this is needed for rpi 3b and maybe rpi zero 1W as well, but as I can't test with those, the change is currently specific to the 2W model
=> Fix bluetooth nor working in RPI zero 2w

src/devices/csaferower/csaferower.cpp, src/devices/csaferower/csaferower.h
Fixes 2 issues in the csafe rower..  
* the deviceFilename variable is not updated, hence a blank port is being opened
* metatype issue: because of void onStatus(uint16_t status);
```
(Make sure 'uint16_t' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'uint16_t'
(Make sure 'uint16_t' is registered using qRegisterMetaType().)
```
=> Fix port on csafe rower

docs/10_Installation.md
Added section to have your treadmill detected and the QZ service automatically started/stopped based on the treadmill state. This is based on the reported bug #2954
=> Included QZ service monitoring

src/main.cpp
I was trying to use qdomyos-zwift with my Horizon 7.8 treadmill and Raspberry Pi and noticed that it wasn't relaying the data correctly, where on my Android it was. I learned that it was due to the two settings, `horizon_treadmill_7_8` and `horizon_treadmill_force_ftms` which can be set from the UX but not the console.
This PR makes them settable via the console!
=> Add two console options to set horizon treadmill settings

src/devices/bluetooth.cpp
My TechnoGym Skillbike is called "BIKE 861" and QZ wouldn't detect it previously because it assumed all such bikes have 4-digit names.
The fix is to relax requirement and detect any /BIKE \d+/ as technogymBike.
=> skillbike: allow 3-digit bikes

src/characteristics/characteristicnotifier2acd.cpp
Currently, qDomyos-zwift's virtual treadmill, when connected via Bluetooth FTMS, **doesn't send "elapsed time" data**. This causes problems for fitness apps like Runna. Without elapsed time, these apps can't correctly calculate metrics leading to **incomplete or "rogue" workout sessions**. Users need to use inconvenient workarounds, like simultaneously recording on a Garmin watch and manually linking the data later.
qDomyos-zwift **starts transmitting "elapsed time"** as part of its Bluetooth FTMS (Fitness Machine Service) data for the virtual treadmill. This means calculating and sending the session's elapsed time during the FTMS broadcast.
* **Better App Compatibility:** Greatly improves how qDomyos-zwift works with third-party fitness apps (like Runna) that rely on FTMS for accurate …
=> feat: Add elapsed time to FTMS virtual treadmill characteristic
