cagnulein/qdomyos-zwift

- src/sportstechbike.cpp
Fix of metrics : 
- Time elapsed from Packet 
- Resistance 
Tested on : rpi0w
> SPORTSTECH Debug Metrics 

- src/keepawakehelper.cpp
- src/keepawakehelper.h
Added a keepScreenOn function for Android to deactivate screen dimming
> Android Srceen dimming Fix:

- src/bluetooth.h
- src/bluetoothdevice.h
- src/homeform.cpp
- src/homeform.h
- src/templateinfosenderbuilder.cpp
- src/templateinfosenderbuilder.h
- src/webserverinfosender.cpp
- src/webserverinfosender.h
- template-examples/youtube-viewer/dash_player.js
- template-examples/youtube-viewer/dash_sost.js
- template-examples/youtube-viewer/globals.js
- template-examples/youtube-viewer/gui.js
- template-examples/youtube-viewer/main_ws_manager.js
- template-examples/youtube-viewer/personal_grabber.js
- template-examples/youtube-viewer/playlist_adder.htm
- template-examples/youtube-viewer/playlist_adder.js
- template-examples/youtube-viewer/qtfetcher.js
- template-examples/youtube-viewer/senereal_yt_sost.js
- template-examples/youtube-viewer/twitch-id.htm
- template-examples/youtube-viewer/twitch_grabber.js
- template-examples/youtube-viewer/twitch_player.js
- template-examples/youtube-viewer/video_manager.js
- template-examples/youtube-viewer/videojs_player.js
- template-examples/youtube-viewer/workout.htm
- template-examples/youtube-viewer/youtube_grabber.js
- template-examples/youtube-viewer/youtube_player.js
Just a small PR in which I
Added the possibility to request a web page body fetch in base64 format
Added twitch palyer and grabber for youtube-viewer plugin (needs ssl or localhost web server)
Added dash palyer for youtube-viewer plugin
Added hls player for youtube-viewer plugin
I hope to be fully compliant to the lilof code style.
> Some more webserver / template features

- src/bluetooth.cpp
- src/domyostreadmill.cpp
- src/domyostreadmill.h
- src/echelonstride.cpp
- src/echelonstride.h
- src/eslinkertreadmill.cpp
- src/eslinkertreadmill.h
- src/fitshowtreadmill.cpp
- src/fitshowtreadmill.h
- src/kingsmithr1protreadmill.cpp
- src/kingsmithr1protreadmill.h
- src/kingsmithr2treadmill.cpp
- src/kingsmithr2treadmill.h
- src/treadmill.cpp
- src/treadmill.h
a `device` isn't a `domyostreadmill`. but every treadmill have to be
subclass of `treadmill`
`setLastSpeed`, `setLastInclination` and `odometer` move to
upper class and change to virtual function
> Fix segfault of `bluetooth::stateFileRead`

- src/trainprogram.cpp
- src/trainprogram.h
- src/zwiftworkout.cpp
- src/zwiftworkout.h
> Trainingprogram distance

- docs/40_web_socket_api.md
As promised in issue #572 here is a complete tutorial on how to install QDomyos-Zwift on a raspberry Pi / Linux but also quickly understand the base API.  (Okay I'm late of one day :sweat_smile:)
(I didn't write all the commands and I don't know how in markdown to ref to another file :eyes:)
Sorry if there are a lot of spelling or grammar mistakes but English is not my mother language and already I have big spelling and grammar problems in French xD (I'm more a guy who program than write docs xD)
> QDomyos-Zwift WebSocket API Installation & Operation guide

- src/WebEngineTest.qml
- src/fitshowtreadmill.cpp
- src/fitshowtreadmill.h
- src/homeform.cpp
- src/homeform.h
- src/m3ibike.cpp
- src/main.qml
- src/qml.qrc
- src/settings.qml
- src/trainprogram.cpp
- src/trainprogram.h
- src/zwiftworkout.cpp
- src/zwiftworkout.h
This branch implements the navigation on whatsonzwift.com to take zwift training programs and load them inside QZ. This branch introduces also some fixes to fitshow treadmill and m3i bike. It should fix anyrun compatibility activating the new settings inside the fitshow section.
> Whatsonzwift

- src/fakebike.cpp
Makes testing a bit easier since the +/- buttons will now work
> Enable resistance changes with fakebike

- .gitignore
- src/homeform.cpp
- src/qdomyos-zwift.pro
- src/secret.h
Prevent the ability to accidentally commit secrets
> Add src/secret.h to .gitignore

- src/SettingsList.qml
- src/homeform.cpp
- src/homeform.h
- src/main.qml
- src/profiles.qml
- src/qdomyos-zwift.pro
- src/qml.qrc
- src/settings.qml
- src/simplecrypt.cpp
- src/simplecrypt.h
Adds a new feature to support multiple profiles on the same device
* Add a new sidebar menu "Profiles: <profile_name>"
* Enables saving current settings as a new Profile
* Enables quickly switching between Profiles
* Enables deleting a Profile by pressing and holding
* Updates existing settings export filenames to be `yyyyMMdd` to be sorted by recent first
|Sidebar|Profiles|
|-|-|
|![Screenshot_1646514307](https://user-images.githubusercontent.com/277030/156899900-4bc0ce60-ec15-4882-9e27-86a9d1eb8f96.png)|![Screenshot_1646805737](https://user-images.githubusercontent.com/277030/157381999-58c48231-7223-490e-9b48-a9c03c7abebf.png)|
> Implement Profiles

- src/bluetooth.cpp
Just copied from official application logs
Related #791
> Add more KingSmith WalkingPad X21

- src/TrainingProgramsList.qml
- src/homeform.cpp
- src/homeform.h
- src/main.qml
- src/qml.qrc
- src/trainprogram.cpp
- src/trainprogram.h
- src/zwiftworkout.cpp
- src/zwiftworkout.h
- src/zwo/Easy intervals.zwo
- src/zwo/HIIT Aerobic.zwo
- src/zwo/HIIT Anaerobic Sprint.zwo
- src/zwo/HIIT Anaerobic.zwo
- src/zwo/HIIT Neuromuscular.zwo
- src/zwo/Short Mix by Jonathan.zwo
- src/zwo/Tabata plus 2 with sweet spot and threshold.zwo
- src/zwo/Tabata with sweet spot.zwo
- src/zwo/Tempo and endurance.zwo
- src/zwo/VO2max with recovery.zwo
- src/zwo/VO2max with sweet spot.zwo
> Zwo chart preview for power zone bike workout

- src/bluetooth.cpp
> #906 add chronobike to template managers

- src/bluetooth.cpp
- src/bluetooth.h
> #927 route starting and stopping of bluetooth discovery through new functions startDiscovery() and stopDiscovery()

- src/Home.qml
- src/homeform.cpp
- src/homeform.h
- src/main.qml
> Video Workout footer 

- src/chronobike.cpp
- src/flywheelbike.cpp
- src/inspirebike.cpp
- src/m3ibike.cpp
- src/proformbike.cpp
- src/proformwifibike.cpp
- src/proformwifitreadmill.cpp
- src/yesoulbike.cpp
> #959 changed default for reading ios_peloton_workaround setting to true

- src/eslinkertreadmill.cpp
- src/eslinkertreadmill.h
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings.qml
This works on my YPOO Mini Change, at least enough to show speed, distance, KCals. It was showing 0.8 as the speed randomly after being on for a minute, when it was still at 0. It can't go less that 1k/h so I just ignored the 0.8. Uses different fields for KCals than the others. Doesn't have inclination, and the field that the other two use seems to just echo distance, so I've made the inclination read just return 0.
> Adding ESLinker YPOO Mini Change treadmill

- src/android/AndroidManifest.xml
- src/android/src/ChannelService.java
- src/android/src/SpeedChannelController.java
- src/main.qml
- src/qdomyos-zwift.pro
- src/settings.qml
> fixed speed value conversion in SpeedChannelController #167

- src/kingsmithr1protreadmill.cpp
- src/kingsmithr2treadmill.cpp
> #1000 removed searchStopped check from virtual device setup

- src/iconceptbike.cpp
- src/iconceptbike.h
> #998 only attempt to set up virtual device on first update

- src/trainprogram.cpp
Fix for INF Calculation in cagnulein#973
> Fix for INF Calculation in cagnulein#973

- src/android/AndroidManifest.xml
- src/android/build.gradle
- src/android/src/ForegroundService.java
- src/android/src/NotificationClient.java
- src/bluetooth.cpp
- src/qdomyos-zwift.pro
> Background operation permanent notification option 

- build-qdomyos-zwift-Qt_5_15_2_for_iOS-Debug/qdomyoszwift.xcodeproj/project.pbxproj
- src/characteristicwriteprocessor.cpp
- src/characteristicwriteprocessor.h
- src/characteristicwriteprocessor2ad9.cpp
- src/characteristicwriteprocessor2ad9.h
- src/characteristicwriteprocessore005.cpp
- src/characteristicwriteprocessore005.h
- src/dirconmanager.cpp
- src/dirconmanager.h
- src/qdomyos-zwift.pro
- src/wahookickrsnapbike.h
> The control of RGT app not working with Wahoo Direct Connect for RGT setting

- src/Computrainer.cpp
- src/Computrainer.h
- src/android/AndroidManifest.xml
- src/android/build.gradle
- src/android/src/Usbserial.java
- src/qdomyos-zwift.pro
@drmason789 maybe you're interested in this too. It works like a charm on my test device
> Usb serial for android

- .github/workflows/main.yml
- src/android/AndroidManifest.xml
- src/android/build.gradle
- src/android/src/QZAdbRemote.java
- src/android/src/com/cgutman/adblib/AdbBase64.java
- src/android/src/com/cgutman/adblib/AdbConnection.java
- src/android/src/com/cgutman/adblib/AdbCrypto.java
- src/android/src/com/cgutman/adblib/AdbProtocol.java
- src/android/src/com/cgutman/adblib/AdbStream.java
- src/android/src/com/cgutman/adblib/package-info.java
- src/android/src/com/cgutman/androidremotedebugger/AdbUtils.java
- src/android/src/com/cgutman/androidremotedebugger/adblib/AndroidBase64.java
- src/android/src/com/cgutman/androidremotedebugger/console/CommandHistory.java
- src/android/src/com/cgutman/androidremotedebugger/console/ConsoleBuffer.java
- src/android/src/com/cgutman/androidremotedebugger/devconn/DeviceConnection.java
- src/android/src/com/cgutman/androidremotedebugger/devconn/DeviceConnectionListener.java
- src/android/src/com/cgutman/androidremotedebugger/service/ShellListener.java
- src/android/src/com/cgutman/androidremotedebugger/service/ShellService.java
- src/android/src/com/cgutman/androidremotedebugger/ui/Dialog.java
- src/android/src/com/cgutman/androidremotedebugger/ui/SpinnerDialog.java
- src/nordictrackifitadbbike.cpp
- src/nordictrackifitadbbike.h
- src/nordictrackifitadbtreadmill.cpp
- src/nordictrackifitadbtreadmill.h
- src/qdomyos-zwift.pro
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/15#issuecomment-1362846094
> ADBRemote 

- src/android/src/ChannelService.java
- src/android/src/SpeedChannelController.java
> issues with ant+ speed sensor fixed by migration to speed and cadence

- tst/Devices/HorizonTreadmill/horizontreadmilltestdata.h
- tst/Devices/TacxNeo2/tacxneo2testdata.h
- tst/Devices/bluetoothdevicetestsuite.cpp
#1144 
Also made the tests more informative.
> #1144 added tests for Thinkrider X5, Noblepro treadmill. 

- docs/10_Installation.md
#1150 I've made some changes to make it build and run under Linux (Ubuntu 22.04).
I've kept these instructions just for building the app.
I won't be in a position to test on the Raspberry Pi for about 1 week.
> Build corrections 1150

- tst/Devices/FTMSBike/ftmsbiketestdata.h
- tst/Devices/PafersTreadmill/paferstreadmilltestdata.h
- tst/Devices/devicediscoveryinfo.cpp
- tst/Devices/devicediscoveryinfo.h
> Test updates 1197

- src/nordictrackelliptical.cpp
Hi @cagnulein I didn't forget about issue #1277 and have found some times to experiment directly on the elliptical.
Some functions didn't appear in the previous logs, like the inclination value when you click on the console panel.
I have also rewritten some if-else if-else to make it easier to read.
In forceResistance, for proform_hybrid_trainer_xt, looks like case 15 and 16 are missing so I added them.
A part that took me some time to understand is that if you want to calculate a uint16_t from a newValue.at(x), you need to make a double conversion (uint16_t)((uint8_t)(newValue.at(1)). If you write (uint16_t)(newValue.at(1)), you'll get a random number...
Everything works fine except the watts value. That value looks too high (more than 150watts) but I'm not sure how it's calculated and …
> Nordictrack_C7.5

- src/eslinkertreadmill.cpp
- src/eslinkertreadmill.h
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings.qml
> Costaway folding treadmill #1350

- src/nordictrackelliptical.cpp
Hi  @cagnulein This is the Resistance fix for #1369
> Fixing Resistance nordictrackelliptical.cpp

- src/tacxneo2.cpp
> Cadence in Wahoo Direct Connect mode #1396

- src/bluetooth.cpp
- src/bluetooth.h
- src/iconceptelliptical.cpp
- src/iconceptelliptical.h
- src/qdomyos-zwift.pri
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings.qml
- tst/Devices/bluetoothdevicetestdata.h
- tst/Devices/devicediscoveryinfo.cpp
- tst/Devices/devicediscoveryinfo.h
- tst/Devices/devices.h
- tst/Devices/iConceptElliptical/iconceptellipticaltestdata.h
- tst/qdomyos-zwift-tests.pro
> BH NLS12 Elliptical

- src/horizontreadmill.cpp
- src/horizontreadmill.h
> KETTLER TM support

- src/android/src/Usbserial.java
- src/android/src/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java
- src/android/src/com/hoho/android/usbserial/driver/Ch34xSerialDriver.java
- src/android/src/com/hoho/android/usbserial/driver/CommonUsbSerialPort.java
- src/android/src/com/hoho/android/usbserial/driver/Cp21xxSerialDriver.java
- src/android/src/com/hoho/android/usbserial/driver/FtdiSerialDriver.java
- src/android/src/com/hoho/android/usbserial/driver/ProbeTable.java
- src/android/src/com/hoho/android/usbserial/driver/ProlificSerialDriver.java
- src/android/src/com/hoho/android/usbserial/driver/SerialTimeoutException.java
- src/android/src/com/hoho/android/usbserial/driver/UsbId.java
- src/android/src/com/hoho/android/usbserial/driver/UsbSerialDriver.java
- src/android/src/com/hoho/android/usbserial/driver/UsbSerialPort.java
- src/android/src/com/hoho/android/usbserial/driver/UsbSerialProber.java
- src/android/src/com/hoho/android/usbserial/util/MonotonicClock.java
- src/android/src/com/hoho/android/usbserial/util/SerialInputOutputManager.java
- src/qdomyos-zwift.pri
> Rowing concept2 pm3, pm4 (bluetooth) #1486

- src/main.cpp
- src/main.qml
- src/settings.qml
Volume keys not working on android even if the volume gears setting is disabled #1524
Code done, I just need to test it
> Volume keys not working on android even if the volume gears setting is disabled #1524

- src/proformbike.cpp
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings.qml
> Pro-form SB - Model # PFEVEX72917S #1507

- .github/workflows/main.yml
- src/android/build.gradle
https://stackoverflow.com/questions/49402451/gradle-task-to-rename-file
> Amazon App Store 64 bit compatibility #1328

- src/homeform.cpp
- src/homeform.h
- src/main.qml
- src/trainprogram.h
> Ability to play a video in sync with ZWO training file #1562

- .github/workflows/main.yml
- qt-patches/windows/5.15.2/qlowenergycontroller_win.cpp
> Runmaxx 9.1 Threadmill on Win 10 (Issue #1581)

- src/android/src/Ant.java
- src/android/src/ChannelService.java
- src/android/src/SDMChannelController.java
- src/bluetooth.cpp
- src/qdomyos-zwift.pri
> ANT+ Running speed sensor #1586

- src/nordictrackifitadbbike.cpp
- src/nordictrackifitadbbike.h
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/59
> HRM from Nordictrack ADB bikes

- docs/10_Installation.md
equipement -> equipment
raspeberry -> Raspberry
> fix: typo error in 10_Installation.md

- README.md
This PR fixes some grammatical errors in the readme file.
> dosc: Fixes typo in README.md

- src/homeform.cpp
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/58#issuecomment-1808920358
> Moving QZ folder to the Documents folder due to the new Android 14 restrictions

- src/bike.cpp
- src/bluetoothdevice.cpp
- src/bluetoothdevice.h
- src/elliptical.cpp
- src/homeform.cpp
- src/qfit.cpp
- src/rower.cpp
- src/treadmill.cpp
> Slight difference between front end pace vs .fit file pace? #1838

- src/homeform.cpp
> impossible to add gpx (Issue #1926)

- src/fitshowtreadmill.cpp
> Atletica Lightspeed Treadmill start issue (Fitshow) #1950

- docs/50_writing_tests.md
>  #2162 updated test documentation to enhance instructions for DeviceDiscoveryInfo

- src/devices/treadmill.cpp
- src/homeform.cpp
- src/homeform.h
- src/metric.cpp
- src/metric.h
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings-tiles.qml
- src/settings.qml
RSS in real time in QZ while using an Stryd Pod #2265
> RSS in real time in QZ while using an Stryd Pod #2265

- src/devices/fitshowtreadmill/fitshowtreadmill.cpp
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings.qml
[No metrics treadmill doesnt react to app BUG]](https://github.com/cagnulein/qdomyos-zwift/issues/2453#top)
#2453
> No metrics treadmill doesnt react to app BUG] #2453

- src/devices/trxappgateusbtreadmill/trxappgateusbtreadmill.cpp
Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions
> Adidas Treadmill #1705 on android

- README.md
These adjustments should make the README more user-friendly and accessible, improving the initial experience for new users and contributors.
> Revised README Layout and Links for Improved Readability

- src/devices/csafe/csafe.cpp
- src/devices/csafe/csafe.h
- src/devices/csaferower/csaferower.cpp
- src/devices/csaferower/csaferower.h
- src/qdomyos-zwift.pri
In preparation to make a clean PR for the LifeFitness CSAFE elliptical. 
Changes:
* This PR moves the csafe lib to a separate folder (serveral csafe related files will be added later to the same folder)
* Adds few csafe commands
* Makes the CSAFE non-standard wrapping optional
* Apply the wrapping to the csaferower
> Move csafe lib to separate folder and add commands

- src/devices/ftmsbike/ftmsbike.cpp
[Inclination Gain implementation in QZ for Elite Suito/Rouvy](https://github.com/cagnulein/qdomyos-zwift/issues/2850#top)
#2850
> Inclination Gain implementation in QZ for Elite Suito/Rouvy #2850

- docker/linux_gui_vnc/Dockerfile
- docker/linux_gui_vnc/build.sh
- docker/linux_gui_vnc/docker-compose.yml
Added files for building and running in Docker with GUI /docker/linux_gui_vnc
> Added files for building and running in Docker with GUI

- docker/linux_gui_vnc/Dockerfile
Added multi-stage build, unnecessary files removed from the image.
> Docker gui vnc

- docker/linux_webgl/Dockerfile
- docker/linux_webgl/build.sh
- docker/linux_webgl/docker-compose.yml
Added build with qtwebglplugin. The web interface is available by default on port 8080. Using docker-compose, you can change the port or run without GUI and with custom parameters.
> Added build with qtwebglplugin

- src/main.cpp
Missed the `i` in my `if` statement 🫠
> Missed a character!

- src/virtualdevices/virtualtreadmill.cpp
- src/virtualdevices/virtualtreadmill.h
https://github.com/cagnulein/qdomyos-zwift/pull/1915
> Garmin discovers but can't connect to cadence sensor (Issue #3023)

- src/devices/heartratebelt/heartratebelt.cpp
- src/devices/heartratebelt/heartratebelt.h
> Polar OH1 not connecting consistently with Android tablet / Qdomyos-swift app #3139

- src/devices/bluetooth.cpp
[No power when pedalling with Van Rysel D500 turbo trainer.](https://github.com/cagnulein/qdomyos-zwift/issues/3065#top)
#3065
> No power when pedalling with Van Rysel D500 turbo trainer. #3065

- src/main.cpp
Testing my BLE Zwift RunPod via the console
> Enable setting power sensor via command line

- src/homeform.cpp
- src/peloton.cpp
- src/peloton.h
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings.qml
Peloton API Login Issues (Issue #3217)
> Peloton API Login Issues (Issue #3217)

- src/devices/ftmsbike/ftmsbike.cpp
Reverting [Rouvy: Virtual shifting with Zwift gearing, noticeably harder than physical gearing](https://github.com/cagnulein/qdomyos-zwift/issues/3031#top)
#3031
> reverting Rouvy: Virtual shifting with Zwift gearing, noticeably harder than physical gearing #3031

- src/devices/domyostreadmill/domyostreadmill.cpp
Inclination overide not working for Domyos T900C (Issue #3267)
> Inclination overide not working for Domyos T900C (Issue #3267)

- src/devices/proformtreadmill/proformtreadmill.cpp
- src/devices/proformtreadmill/proformtreadmill.h
- src/main.cpp
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings.qml
NB : not able to make start and stop action work, all the rest work well (data gathering, speed and inclination set, ...)
Linked to #3285
> feat: add Proform performance 300i

- .github/workflows/main.yml
- .gitmodules
- src/localipaddress.cpp
Dircon doesn't work on android 13 and 14 (Issue #3325)
> Dircon doesn't work on android 13 and 14 (Issue #3325)

- .gitignore
- src/devices/bluetoothdevice.cpp
- src/devices/bluetoothdevice.h
- src/homeform.cpp
- src/homeform.h
- src/qzsettings.cpp
- src/qzsettings.h
- src/settings-tiles.qml
- src/settings.qml
> Core temperature sensor tiles
